// <auto-generated />
using System;
using Licitation.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Licitation.API.Migrations
{
    [DbContext(typeof(LicitationDBContext))]
    [Migration("20230218175857_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Licitation.API.Entities.Document", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCertified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<Guid>("LicitationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Template")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Guid");

                    b.HasIndex("LicitationGuid");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasFilter("[ReferenceNumber] IS NOT NULL");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("3eaae99e-7690-4476-ab92-213bf3a2ea58"),
                            DateCertified = new DateTime(2022, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateSubmitted = new DateTime(2021, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DocumentType = 1,
                            LicitationGuid = new Guid("e053576b-8397-4173-928e-dec58721d00f"),
                            ReferenceNumber = "34",
                            Template = "Sablon dokumenta"
                        });
                });

            modelBuilder.Entity("Licitation.API.Entities.Licitation", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("BidIncrement")
                        .HasColumnType("int");

                    b.Property<int>("Constarint")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("LicitationEntities");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("e053576b-8397-4173-928e-dec58721d00f"),
                            ApplicationDeadline = new DateTime(2023, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BidIncrement = 100,
                            Constarint = 0,
                            Date = new DateTime(2023, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stage = 2,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Licitation.API.Entities.LicitationLand", b =>
                {
                    b.Property<Guid>("LandGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicitationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LicitationGuid1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LandGuid", "LicitationGuid");

                    b.HasIndex("LicitationGuid");

                    b.HasIndex("LicitationGuid1");

                    b.ToTable("LicitationLands");
                });

            modelBuilder.Entity("Licitation.API.Entities.PublicBidding", b =>
                {
                    b.Property<Guid>("PublicBiddingGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicitationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LicitationGuid1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PublicBiddingGuid", "LicitationGuid");

                    b.HasIndex("LicitationGuid");

                    b.HasIndex("LicitationGuid1");

                    b.ToTable("LicitationPublicBiddings");
                });

            modelBuilder.Entity("Licitation.API.Entities.Document", b =>
                {
                    b.HasOne("Licitation.API.Entities.Licitation", "licitation")
                        .WithMany("Documents")
                        .HasForeignKey("LicitationGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("licitation");
                });

            modelBuilder.Entity("Licitation.API.Entities.LicitationLand", b =>
                {
                    b.HasOne("Licitation.API.Entities.Licitation", "licitation")
                        .WithMany("LicitationLands")
                        .HasForeignKey("LicitationGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licitation.API.Entities.Licitation", null)
                        .WithMany("Lands")
                        .HasForeignKey("LicitationGuid1");

                    b.Navigation("licitation");
                });

            modelBuilder.Entity("Licitation.API.Entities.PublicBidding", b =>
                {
                    b.HasOne("Licitation.API.Entities.Licitation", "licitation")
                        .WithMany("PublicBiddings")
                        .HasForeignKey("LicitationGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licitation.API.Entities.Licitation", null)
                        .WithMany("LicitationPublicBiddings")
                        .HasForeignKey("LicitationGuid1");

                    b.Navigation("licitation");
                });

            modelBuilder.Entity("Licitation.API.Entities.Licitation", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Lands");

                    b.Navigation("LicitationLands");

                    b.Navigation("LicitationPublicBiddings");

                    b.Navigation("PublicBiddings");
                });
#pragma warning restore 612, 618
        }
    }
}
