// <auto-generated />
using System;
using Licitation.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Licitation.API.Migrations
{
    [DbContext(typeof(LicitationDBContext))]
    [Migration("20230212154201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Licitation.API.Entities.Document", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCertified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LicitationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("documentType")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.HasIndex("LicitationGuid");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique();

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Licitation.API.Entities.LicitationEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("BidIncrement")
                        .HasColumnType("int");

                    b.Property<int>("Constarint")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("LicitationEntities");
                });

            modelBuilder.Entity("Licitation.API.Entities.LicitationLand", b =>
                {
                    b.Property<Guid>("Licitation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LandGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LicitationEntityGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Licitation", "LandGuid");

                    b.HasIndex("LicitationEntityGuid");

                    b.ToTable("LicitationLands");
                });

            modelBuilder.Entity("Licitation.API.Entities.LicitationPublicBidding", b =>
                {
                    b.Property<Guid>("PublicBiddingGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Licitation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LicitationEntityGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PublicBiddingGuid", "Licitation");

                    b.HasIndex("Licitation");

                    b.HasIndex("LicitationEntityGuid");

                    b.ToTable("LicitationPublicBiddings");
                });

            modelBuilder.Entity("Licitation.API.Entities.Document", b =>
                {
                    b.HasOne("Licitation.API.Entities.LicitationEntity", "licitationEntity")
                        .WithMany("Documents")
                        .HasForeignKey("LicitationGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("licitationEntity");
                });

            modelBuilder.Entity("Licitation.API.Entities.LicitationLand", b =>
                {
                    b.HasOne("Licitation.API.Entities.LicitationEntity", "licitationEntity")
                        .WithMany("LicitationLands")
                        .HasForeignKey("Licitation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licitation.API.Entities.LicitationEntity", null)
                        .WithMany("LandGuids")
                        .HasForeignKey("LicitationEntityGuid");

                    b.Navigation("licitationEntity");
                });

            modelBuilder.Entity("Licitation.API.Entities.LicitationPublicBidding", b =>
                {
                    b.HasOne("Licitation.API.Entities.LicitationEntity", "licitationEntity")
                        .WithMany("LicitationPublicBiddings")
                        .HasForeignKey("Licitation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licitation.API.Entities.LicitationEntity", null)
                        .WithMany("PublicBiddingGuids")
                        .HasForeignKey("LicitationEntityGuid");

                    b.Navigation("licitationEntity");
                });

            modelBuilder.Entity("Licitation.API.Entities.LicitationEntity", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LandGuids");

                    b.Navigation("LicitationLands");

                    b.Navigation("LicitationPublicBiddings");

                    b.Navigation("PublicBiddingGuids");
                });
#pragma warning restore 612, 618
        }
    }
}
