// <auto-generated />
using System;
using Lease.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lease.API.Migrations
{
    [DbContext(typeof(LeaseDbContext))]
    partial class LeaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lease.API.Entities.Buyer", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ban")
                        .HasColumnType("bit");

                    b.Property<int>("BanDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("BanEndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BiddingGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priorities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RealisedArea")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateOfBan")
                        .HasColumnType("datetime2");

                    b.HasKey("Guid");

                    b.HasIndex("PersonGuid")
                        .IsUnique();

                    b.ToTable("Buyers");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("600f70cc-2384-4ea7-95fa-9ef269736e3f"),
                            Ban = false,
                            BanDuration = 0,
                            BanEndDate = new DateTime(2023, 2, 17, 16, 33, 22, 979, DateTimeKind.Local),
                            BiddingGuid = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            PersonGuid = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            Priorities = "[2,1]",
                            RealisedArea = 20,
                            StartDateOfBan = new DateTime(2023, 2, 17, 16, 33, 22, 979, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Lease.API.Entities.Document", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCertified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSubbmitted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LeaseAgreementGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Template")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.HasIndex("LeaseAgreementGuid");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasFilter("[ReferenceNumber] IS NOT NULL");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            DateCertified = new DateTime(2023, 2, 17, 15, 35, 11, 651, DateTimeKind.Utc),
                            DateSubbmitted = new DateTime(2023, 2, 17, 15, 35, 11, 651, DateTimeKind.Utc),
                            LeaseAgreementGuid = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            ReferenceNumber = "lll",
                            Template = "SV obrazac",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Lease.API.Entities.DueDate", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DueDateGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.ToTable("DueDates");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("b415d4f5-6342-41f3-9935-08db10fc223b"),
                            Date = new DateTime(2023, 1, 17, 15, 32, 2, 236, DateTimeKind.Unspecified),
                            DueDateGuid = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("Lease.API.Entities.LeaseAgreement", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfSigning")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRecording")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeadlineLandReturn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("DueDateGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GuaranteeType")
                        .HasColumnType("int");

                    b.Property<Guid>("MinisterGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaceOfSigning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PublicBiddingGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Guid");

                    b.HasIndex("DueDateGuid");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasFilter("[ReferenceNumber] IS NOT NULL");

                    b.ToTable("LeaseAgreements");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            DateOfSigning = new DateTime(2023, 2, 18, 17, 18, 11, 961, DateTimeKind.Local),
                            DateRecording = new DateTime(2023, 2, 18, 17, 18, 11, 961, DateTimeKind.Local),
                            DeadlineLandReturn = new DateTime(2023, 2, 18, 17, 18, 11, 961, DateTimeKind.Local),
                            DocumentStatus = 0,
                            DueDateGuid = new Guid("b415d4f5-6342-41f3-9935-08db10fc223b"),
                            GuaranteeType = 0,
                            MinisterGuid = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            PersonGuid = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            PlaceOfSigning = "string",
                            PublicBiddingGuid = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            ReferenceNumber = "string"
                        });
                });

            modelBuilder.Entity("Lease.API.Entities.Buyer", b =>
                {
                    b.HasOne("Lease.API.Entities.LeaseAgreement", "LeaseAgreement")
                        .WithOne("Buyer")
                        .HasForeignKey("Lease.API.Entities.Buyer", "PersonGuid")
                        .HasPrincipalKey("Lease.API.Entities.LeaseAgreement", "PersonGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaseAgreement");
                });

            modelBuilder.Entity("Lease.API.Entities.Document", b =>
                {
                    b.HasOne("Lease.API.Entities.LeaseAgreement", "LeaseAgreement")
                        .WithMany("Documents")
                        .HasForeignKey("LeaseAgreementGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaseAgreement");
                });

            modelBuilder.Entity("Lease.API.Entities.LeaseAgreement", b =>
                {
                    b.HasOne("Lease.API.Entities.DueDate", "DueDate")
                        .WithMany("LeaseAgreements")
                        .HasForeignKey("DueDateGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DueDate");
                });

            modelBuilder.Entity("Lease.API.Entities.DueDate", b =>
                {
                    b.Navigation("LeaseAgreements");
                });

            modelBuilder.Entity("Lease.API.Entities.LeaseAgreement", b =>
                {
                    b.Navigation("Buyer");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
